version: '3'
services:
  laravel-csv-import-nginx:
    container_name: "laravel-csv-import-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel-csv-import-app
    ports:
      - 80:80
      - 8008:8008
    volumes:
      - ./:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  laravel-csv-import-app:
    container_name: "laravel-csv-import-app"
    build:
      context: ./docker/php
    depends_on:
      - laravel-csv-import-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  laravel-csv-import-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "laravel-csv-import-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_csv-import
    ports:
      - 3306:3306

  laravel-csv-import-adminer:
    container_name: laravel-csv-import-adminer
    image: adminer:4.7-standalone
    environment:
      # ホストの初期値
      ADMINER_DEFAULT_SERVER: laravel-csv-import-mysql
      # デザイン
      ADMINER_DESIGN: ng9
    # 8080 ポートに割り当て
    ports:
      - "8080:8080"

  laravel-csv-import-redis:
    image: redis:alpine
    container_name: "laravel-csv-import-redis"
    ports:
      - 16379:6379
